apiVersion: v1
kind: Service
metadata:
  name: node0-lb
  labels:
    scope: playground
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-name: besu-test-node0
  finalizers:
    - service.k8s.aws/resources
spec:
  type: LoadBalancer
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: p2pudp
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: p2ptcp

---

apiVersion: v1
kind: Service
metadata:
  name: node1-lb
  labels:
    scope: playground
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-name: besu-test-node1
  finalizers:
    - service.k8s.aws/resources
spec:
  type: LoadBalancer
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: p2pudp
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: p2ptcp

---
