bootnodes=["enode://ea51aef0bc49865b95cbe37b29f23c69c7a7709c0cacac687ada7e310390a95207a6f84bb469084be2d32d3acfa080abd5390468210db94a7bc00ee8e45904a5@node0.dmlkh-besu.svc.cluster.local:30303"]
data-path="/etc/data"
discovery-enabled=true
genesis-file="/etc/config/genesis/genesis.json"
host-allowlist=["*"]
logging="DEBUG"
max-peers=25
node-private-key-file="/etc/keys/key"
p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
revert-reason-enabled=true
rpc-http-api=["DEBUG", "ETH", "WEB3", "NET", "TRACE", "QBFT", "TXPOOL", "ADMIN", "PERM", "EEA", "PRIV"]
rpc-http-authentication-enabled=false
rpc-http-cors-origins=["all"]
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-max-active-connections=80
rpc-http-port=8545
rpc-ws-api=["DEBUG", "ETH", "WEB3", "NET", "TRACE", "QBFT", "TXPOOL", "ADMIN", "PERM", "EEA", "PRIV"]
rpc-ws-authentication-enabled=false
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-max-active-connections=80
rpc-ws-port=8546
